env: sc2

env_args:
  continuing_episode: False
  difficulty: "7"
  game_version: null
  map_name: "4m" # Tasks. hard: 4m, 8m, 16m, 32m, 2s3z, 5s10z, MMM, MMM2
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: ""
  replay_prefix: ""
  state_last_action: True # default: True, False for transfer
  state_timestep_number: False
  step_mul: 8
  seed: null
  heuristic_ai: False
  heuristic_rest: False
  debug: False

seed: 317349183

td_lambda: 0.6 # 0.3 for 6h_vs_8z

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 1050000
obs_agent_id: False # Include the agent's one_hot id in the observation, default: True, False for transfer
obs_last_action: False # Include the agent's last action (one_hot) in the observation, default: True, False for transfer

#batch_size: 128 # for 4m, 8m, 2s3z
batch_size: 64 # for 16m, MMM2, MMM4, 5s10z
#batch_size: 32 # for 32m

# for test MMM2
#checkpoint_path: "../results/models/evol_MMM2" # Load a checkpoint from this path
#evaluate: True # Evaluate model for test_nepisode episodes and quit (no training)
#runner: "episode" # episode