# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0 # default: 1.0, 0.2 for transfer
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z

runner: "parallel" # episode
batch_size_run: 8 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000
batch_size: 128

t_max: 2050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "hpn_mac" # n_mac, hpn_mac
agent: "tree_rnn" # n_rnn, hpns_rnn, tree_rnn

hpn_hyper_dim: 64
hpn_hyper_activation: 'relu'

hpn_head_num: 1 # 2 for 3s_vs_5z and 6h_vs_8z
dernet_head_num: 4
agent_output_type: q

learner: "nq_have_learner" # nq_learner, nq_hmas_learner
mixer: "set_qmix" # qmix, set_qmix
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.001 # Learning rate for agents
td_lambda: 0.6 # 0.3 for 6h_vs_8z
optimizer: 'adam'
q_lambda: False


name: "have"

obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation