# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000
evaluation_epsilon: 0.0

# use parallel
runner: "gymma_parallel" # gymma_parallel, gymma_episode
batch_size_run: 8
buffer_size: 5000
batch_size: 64

# update the target network every {} episodes
target_update_interval_or_tau: 0.001

mac: "basic_mac"
agent: "rnn"

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"

# use for joint action-value network
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# use for individual action-value network
use_rnn: True
double_q: True
td_lambda: 0.6
#lr: 0.0005
#optimizer: 'adam'


obs_agent_id: True
obs_last_action: True
#obs_individual_obs: False
standardise_returns: False
standardise_rewards: False

name: "qmix"
